server:
  port: 9000
  error:
    include-message: always
spring:
  application:
    name: issue-tracker
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    initialization-mode: never
    continue-on-error: true
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:issuetrackerdb
    username: sa
    password:
  h2:
    console:
      enabled: true
